[package]
name = "shrimpy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytemuck = "1.22.0"
chrono = "0.4.41"
image = "0.25.6"
pollster = "0.4.0"
wgpu = "25.0.0"
winit = "0.30.9"
